
CXXFLAGS += -I. -DSHARED_LOWLEVEL -DCOMPILE_TIME_MIN_LEVEL=LEVEL_DEBUG -DUSE_STACK -DUSE_xtask -DUSE_ALLOC 
#-DDEBUG_LOW_LEVEL -DDEBUG_HIGH_LEVEL 
#-I$(srctree)/include/EASTL
obj-y += nt_init_xtask.o \
		 xtask_main.o 	     \
		 xtask.o         \

